version: '2'

services:

  wasmd:
    container_name: wasmd
    image: pppatil/wasmd
    tty: true
    stdin_open: true
    environment:
      - CHAIN_ID="gbcchain"
      - TXFLAG="--chain-id gbcchain --gas-prices 20stake --gas auto --gas-adjustment 1.3"
      - RUSTFLAGS='-C link-arg=-s'
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./wasmd:/wasmd
      - ./cw-examples:/home/cw
      - ./bin:/root/go/bin/:z
